apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
     - name: default
       protocol: layer2
       addresses:
         - "172.20.255.1 - 172.20.255.255"
# ubuntu
# sudo ip route add 172.20.255.0/24 via 192.168.49.2
# https://faun.pub/metallb-configuration-in-minikube-to-enable-kubernetes-service-of-type-loadbalancer-9559739787df
